import { readFileSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname);

function findCssFiles(dir) {
	const files = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const fullPath = join(dir, entry.name);
		if (entry.isDirectory()) {
			files.push(...findCssFiles(fullPath));
		} else if (entry.isFile() && entry.name.endsWith(".css")) {
			files.push(fullPath);
		}
	}
	return files;
}

function collectThemeColors() {
	const colors = new Set();
	for (const file of findCssFiles(join(ROOT, "src"))) {
		const css = readFileSync(file, "utf-8");
		const themeMatch = css.match(/@theme\s*\{([^}]+)\}/);
		if (!themeMatch) continue;
		const colorRegex = /--color-([^:]+):/g;
		let match;
		while ((match = colorRegex.exec(themeMatch[1])) !== null) {
			colors.add(match[1].trim());
		}
	}
	return [...colors];
}

const colorNames = collectThemeColors();
const tailwindColorUtilities = [
	"text-",
	"decoration-",
	"caret-",
	"bg-",
	"border-",
	"border-t-",
	"border-r-",
	"border-b-",
	"border-l-",
	"border-x-",
	"border-y-",
	"divide-",
	"divide-t-",
	"divide-r-",
	"divide-b-",
	"divide-l-",
	"divide-x-",
	"divide-y-",
	"outline-",
	"ring-",
	"shadow-",
	"fill-",
	"stroke-",
	"accent-"
];

const spacingUtilities = [
	"p-",
	"px-",
	"py-",
	"pt-",
	"pr-",
	"pb-",
	"pl-",
	"m-",
	"mx-",
	"my-",
	"mt-",
	"mr-",
	"mb-",
	"ml-",
	"-m-",
	"-mx-",
	"-my-",
	"-mt-",
	"-mr-",
	"-mb-",
	"-ml-",
	"gap-",
	"gap-x-",
	"gap-y-",
	"space-x-",
	"space-y-",
	"-space-x-",
	"-space-y-",
	"w-",
	"h-",
	"size-",
	"scroll-m-",
	"scroll-mx-",
	"scroll-my-",
	"scroll-mt-",
	"scroll-mr-",
	"scroll-mb-",
	"scroll-ml-",
	"scroll-p-",
	"scroll-px-",
	"scroll-py-",
	"scroll-pt-",
	"scroll-pr-",
	"scroll-pb-",
	"scroll-pl-",
	"inset-",
	"inset-x-",
	"inset-y-",
	"-inset-",
	"-inset-x-",
	"-inset-y-",
	"top-",
	"right-",
	"bottom-",
	"left-",
	"-top-",
	"-right-",
	"-bottom-",
	"-left-",
	"translate-x-",
	"translate-y-",
	"-translate-x-",
	"-translate-y-"
];

const colorPatterns = colorNames.length
	? tailwindColorUtilities.map((prefix) => new RegExp(`^\\.${prefix}(${colorNames.join("|")})$`))
	: [];

/** @type {import('stylelint').Config} */
export default {
	extends: ["stylelint-config-standard"],
	rules: {
		"at-rule-no-unknown": [
			true,
			{
				ignoreAtRules: ["theme", "utility", "variant", "apply", "config", "import", "plugin"]
			}
		],
		"function-no-unknown": [
			true,
			{
				ignoreFunctions: ["theme"]
			}
		],
		"no-duplicate-selectors": true,
		"import-notation": "string",
		"declaration-block-no-duplicate-properties": true,
		"selector-pseudo-class-no-unknown": [true, { ignorePseudoClasses: ["global"] }],
		"selector-class-pattern": null,
		"custom-property-pattern": null,
		"selector-disallowed-list": [
			[...spacingUtilities.map((prefix) => new RegExp(`^\\.${prefix}`)), ...colorPatterns],
			{
				message: (selector) =>
					`Don't write "${selector}" manually. It is automatically generated by your @theme Tailwind v4.`
			}
		]
	},
	overrides: [
		{
			files: ["**/*.svelte"],
			customSyntax: "postcss-html",
			rules: {
				"no-empty-source": null
			}
		}
	]
};
