import { writable } from "@amadeus-it-group/tansu";

export const inventoryTranslations$ = writable({
	star: 'Étoile',
	procuration: 'Procuration',
	deliveryNote: 'Bon de livraison',
	axe: 'Hache',
	notebook: 'Carnet',
	telegram: 'Télégramme',
	poster: 'Affiche',
	hammer: 'Marteau',
	file: 'Lime',
	handcuffs: 'Menottes',
	trunkKey: 'Clé de coffre',
	goldSack: "Sac d'or",
	money: 'Argent',
	revolver: 'Revolver',
	barber: 'Barbier',
	shaved: 'Rasé',
	razor: 'Rasoir',
	pencil: 'Crayon',
	canvasBag: 'Sac en toile',
	woodenBox: 'Caisse en bois',
	knife: 'Couteau',
	crowbar: 'Pied-de-biche',
	oldRifle: 'Vieux fusil',
	canteen: 'Gourde',
	pastorRobe: 'Robe de pasteur',
	key: 'Clé',
	suitcase: 'Valise',
	matches: 'Allumettes',
	dynamite: 'Dynamite',
	combination: 'Combinaison'
});